### ISSUE TITLE
How should we pull in changes from upstream trustify?

### ISSUE THREAD

**Issue by jcrossley3** [trustification/rhtpa#13]
Can we automate a regular pull?

**Comment by helio-frota** [comment]
that's a good question...
let's ask to Max if is "correct" to assign permissions to the bot to push to the main [?]

**Comment by jcrossley3** [comment]
@desmax74 is this possible? How do you achieve this in v1?

**Comment by desmax74** [comment]
@jcrossley3 on every pr will start a build with the changes if you configure the branch on konflux. Every pr produce a new image and push on a public quay repo.

**Comment by jcrossley3** [comment]
@desmax74 right, but konflux is monitoring this repo, which is a fork of our [main development repo](https://github.com/trustification/trustify). We'd like for konflux to produce a new image when PR's are merged upstream in https://github.com/trustification/trustify. Essentially, we want this repo, https://github.com/trustification/rhtpa, then one konflux knows about, to "mirror" its upstream, which konflux knows nothing about.

I was thinking we could regularly pull upstream changes into this repo -- preferably automatically, but I'd settle for manual if it's a straightforward process -- hence triggering konflux.

Possible?

**Comment by jcrossley3** [comment]
After a lot of trial and error, I have [this workflow](https://github.com/trustification/rhtpa/blob/0fec5dffb20970554aa9ea3b02204e5dfb4c39e9/.github/workflows/sync.yml) regularly merging changes from upstream trustify into this repo.

Once development stabilizes, we can turn the auto-merge off and be more strategic about cherry-picking upstream changes.

The action requires a [token](https://github.com/trustification/rhtpa/blob/0fec5dffb20970554aa9ea3b02204e5dfb4c39e9/.github/workflows/sync.yml#L31) with `workflow` permission in order to merge changes beneath `.github/workflows/`
